server:
  port: 8100

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_user_crm
    username: postgres
    password: motdepasse123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      defer-datasource-initialization: true 
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true
